---
- name: Mise à jour et configuration Sentinel  
  hosts: all
  become: yes  
  tasks:    
  - name: Mettre à jour le système
    apt:        
      update_cache: yes        
      upgrade: dist

# Python / ufw / Fail2ban