---
- name: Setup sentinel agent
  hosts: applications
  become: yes
  tasks:
  - name: Créer le répertoire Sentinel
    file:
      path: /opt/sentinel
      state: directory
      mode: '0755'

  - name: Copier le script sentinel_agent.py
    copy:
      src: ~/nova-sentinel-infra/ansible/files/sentinel_agent.py
      dest: /opt/sentinel/sentinel_agent.py
      mode: '0755'

  - name: Créer le répertoire de logs Sentinel
    file:
      path: /var/log/sentinel
      state: directory
      mode: '0777'


  - name: Déployer le service systemd Sentinel
    template:
      src: ~/nova-sentinel-infra/ansible/templates/sentinel.service.j2
      dest: /etc/systemd/system/sentinel.service


  - name: Activer et démarrer Sentinel
    systemd:
      name: sentinel
      enabled: yes
      state: started