---

- name: Sentinel update and configuration 
  hosts: all
  become: yes  
  tasks:    
  - name: Update system
    ansible.builtin.apt:        
      update_cache: yes        
      upgrade: dist
  
  - name: Ensure apt-utils is installed
    ansible.builtin.apt:
      name: apt-utils
      state: present
  
  - name: Install python3 and python3-pip
    ansible.builtin.apt:
      name:
        - "python3"
        - "python3-pip"
      state: present
      install_recommends: false

  - name: Ensure pip exists and get path
    ansible.builtin.command: 
      cmd: which pip
    register: pip_path
    failed_when: false
    changed_when: false

  - name: Install psutil 
    ansible.builtin.pip:
      name: psutil
      executable: "{{ pip_path.stdout | default('pip3') }}"
      state: present

  - name: Install iptables
    ansible.builtin.apt:
      name: iptables
      state: present

  - name: Install ufw
    ansible.builtin.apt:
      name: ufw
      state: present

  - name: Enable UFW 
    ansible.builtin.ufw: 
      state: enabled
    retries: 3
    delay: 5

  # Setup UFW rules
  - name: Allow incoming from 192.168.56.1 (master)
    ansible.builtin.ufw:
      from_ip: '192.168.56.1'
      to_port: '2222'
      rule: allow
      direction: in

  - name: Default deny incoming 
    ansible.builtin.ufw:
      default: deny
      direction: incoming

  - name: Default allow outgoing 
    ansible.builtin.ufw:
      default: allow
      direction: outgoing
